name: mysql
services:
  database:
    image: mysql:9.0.1
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=jpa
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
#      - ./my.cnf:/etc/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p${MYSQL_PASSWORD}"]
      timeout: 10s
      retries: 3
      interval: 15s
      start_period: 30s
    mem_reservation: 128M
    networks:
      - docker_network

networks:
  docker_network:
    name: docker_network
    external: true

volumes:
  mysql_data:
    name: mysql_data
    driver: local

